### ISSUE TITLE
python3.8 cmislib3  'RepositoryService' object has no attribute 'binding'

### ISSUE THREAD

**Issue by wlmost** [luca-92/cmislib3#6]
Hello.
If I use not the default repository I got following error
`
>>> target_type_def = repo.getTypeDefinition('Ausfuhrdokumente')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/cmislib/atompub/binding.py", line 1425, in getTypeDefinition
    objectType.reload()
  File "/usr/local/lib/python3.8/site-packages/cmislib/atompub/binding.py", line 3300, in reload
    result = self._cmisClient.binding.get(byTypeIdUrl.encode('utf-8'),
AttributeError: 'RepositoryService' object has no attribute 'binding'
>>>
`
So, how can avoid this error.

**Comment by domcross** [comment]
@wlmost I ran into this bug when trying to call `getObject`, following works for me:
```
client = CmisClient(cmis_url, username, password)
repo = client.getRepository('MY_REPOSITORY')
# workaround for bug 'RepositoryService' object has no attribute 'binding'
repo._cmisClient = client
```
